// Built-in presets for common styles/BPMs. Values are tuned to work with
// the current mapping and audio engine. Users can still override via sliders.

export const BUILT_IN_PRESETS = {
  'bizzuirh': {
    audio: {
      // Tuned for ~114 BPM, drum & bass-heavy responsiveness (without touching color)
      smoothing: 0.58,
      lowHz: 175,
      midHz: 2350,
      beatCooldown: 410,
      subHz: 85,
      envAttack: 0.64,
      envRelease: 0.16,
      agcEnabled: true,
      agcDecay: 0.995,
      drop: { enabled: true, flux: 1.45, bass: 0.58, centroidSlope: 0.022, minBeats: 6, cooldownMs: 6200 },
    },
    visuals: { bloomReactive: 0.82 },
    mapping: {
      // Broad reactivity across bands; color-related mapping left intact elsewhere
      sizeFromRms: 0.58,
      sphereBrightnessFromRms: 1.7,
      sphereNoiseFromMid: 1.25,
      ringScaleFromBands: 0.46,
      ringSpeedFromBands: 1.9,
      ringNoiseFromBands: 0.52,
      cameraShakeFromBeat: 0.36,
      lightIntensityFromBass: 2.5,
      ringTiltFromBass: 0.68,
      starTwinkleFromTreble: 1.2,
      spherePulseFromBass: 1.05,
      sphereSparkleFromTreble: 0.88,
      fovPumpFromBass: 0.70,
      bandWeightBass: 1.30,
      bandWeightMid: 1.10,
      bandWeightTreble: 1.05,
      cameraRollFromCentroid: 0.20,
      mainSwayFromFlux: 0.16,
      chromaLightInfluence: 0.30,
      ringBrightFromChroma: 0.36,
      advancedMapping: true,
      sizeWeights: { bass: 1.08, mid: 0.56, treble: 0.22 },
      ringScaleWeights: { bass: 0.88, mid: 0.60, treble: 0.24 },
      ringSpeedWeights: { bass: 0.34, mid: 1.08, treble: 0.40 },
      sphereNoiseWeights: { bass: 0.21, mid: 1.00, treble: 0.41 },
      ringNoiseWeights: { bass: 0.34, mid: 0.66, treble: 0.34 },
      drop: { intensity: 1.0, bloomBoost: 0.55, shake: 0.50, ringBurst: 0.60 },
    },
  },
  'Rave Mode': {
    audio: {
      smoothing: 0.58,
      lowHz: 180,
      midHz: 2400,
      beatCooldown: 320,
      subHz: 85,
      envAttack: 0.70,
      envRelease: 0.12,
      agcEnabled: true,
      agcDecay: 0.995,
      noiseGateEnabled: true,
      noiseGateThreshold: 0.12,
      beatEnergyFloor: 0.30,
      drop: { enabled: true, flux: 1.45, bass: 0.60, centroidSlope: 0.020, minBeats: 6, cooldownMs: 6500, barGateEnabled: true, beatsPerBar: 4, downbeatToleranceMs: 80, useBassFlux: true, autoThresholds: true },
    },
    visuals: { bloomReactive: 0.95 },
    mapping: {
      sizeFromRms: 0.62,
      sphereBrightnessFromRms: 1.95,
      sphereNoiseFromMid: 1.35,
      ringScaleFromBands: 0.52,
      ringSpeedFromBands: 2.2,
      ringNoiseFromBands: 0.60,
      cameraShakeFromBeat: 0.50,
      lightIntensityFromBass: 2.9,
      ringTiltFromBass: 0.76,
      starTwinkleFromTreble: 1.35,
      spherePulseFromBass: 1.18,
      sphereSparkleFromTreble: 1.00,
      fovPumpFromBass: 0.85,
      bandWeightBass: 1.40,
      bandWeightMid: 1.15,
      bandWeightTreble: 1.10,
      cameraRollFromCentroid: 0.26,
      mainSwayFromFlux: 0.22,
      chromaLightInfluence: 0.34,
      ringBrightFromChroma: 0.40,
      advancedMapping: true,
      sizeWeights: { bass: 1.16, mid: 0.60, treble: 0.24 },
      ringScaleWeights: { bass: 0.94, mid: 0.66, treble: 0.26 },
      ringSpeedWeights: { bass: 0.38, mid: 1.16, treble: 0.46 },
      sphereNoiseWeights: { bass: 0.24, mid: 1.06, treble: 0.44 },
      ringNoiseWeights: { bass: 0.36, mid: 0.70, treble: 0.36 },
      drop: { intensity: 1.6, bloomBoost: 0.75, shake: 0.60, ringBurst: 0.80 },
    },
  },
};




